cursor #dee3e5
cursor_text_color #bfc8ca

foreground            #dee3e5
background            #0e1416
selection_foreground  #1c3438
selection_background  #b1cbd0
url_color             #82d3e1

color0   #0e1416
color1   #ff72a2
color2   #70e17b
color3   #fff572
color4   #69c5d5
color5   #175c68
color6   #82d3e1
color7   #deeaec
color8   #879092
color9   #ff9fc0
color10  #a5ffae
color11  #fff8a5
color12  #9eeaf7
color13  #b3f3ff
color14  #cef7ff
color15  #f8feff
